views:
  groupBits:
    TowerBars: 1
    TowerVintageLights: 2
    DJ Lights: 4
    WallVintageLights: 8
    Redwoods1: 16
    Redwoods2: 32
    Redwoods3: 256
    WallVintageLightsTop: 512
    LedBarsWall: 1024
  custom:
    - name: RedwoodPARs
      bit: 64
      groups:
        - Redwoods1
        - Redwoods2
        - Redwoods3
    - name: VintageOnly
      bit: 128
      groups:
        - TowerVintageLights
        - WallVintageLights
        - WallVintageLightsTop
